# Generated by Django 2.1.7 on 2019-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('io', models.CharField(max_length=255)),
                ('tu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
